@startuml

title Apply Genome Filter

MetadataFilterControl -> Server: validateFilter()
Server --> MetadataFilterControl: genome_set_id
MetadataFilterControl -> GenomeWidget: updateGenomeSet(genome_set_id)
GenomeWidget -> GroupModels: updateGenomeSet(genome_set_id)
GroupModels -> GroupModel: getGroup(genome_set_id)
GroupModel --> GroupModels: GroupModel
GroupModels --> GenomeWidget: GroupModels
par
GenomeWidget -> GenomeVizControllers: trigger("genomeSetUpdate", this)
GenomeVizControllers -> GenomeViz: genomeSetUpdate()
GenomeWidget -> GroupVizControllers: trigger("genomeSetUpdate", this)
GroupVizControllers -> GroupViz: genomeSetUpdate()
end



@enduml