@startuml
left to right direction
title Phylogenetic Genome Tree Use Cases

:User - single genome: as User1
:User - genome group: as User2

usecase U1 as "Identify evolutionarily similar genomes & their properties"

usecase U2 as "Summarize common / unique properties for evolutionarily similar genomes"

usecase U3 as "Select group of evolutionary-related genomes for analysis"

usecase U4 as "See how group is related evolutionarily"

usecase U5 as "See position of genome in tree"

usecase U6 as "Download tree"

User2 --> U4
User2 --> U3
User2 --> U2
User2 --> U6
User1 --> U5
User1 --> U1
User1 --> U6

U1 <|-- U2 : extends
U5 <|-- U4 : extends

note right of U2
  Find meta-data, geographic locations, etc. The tree
  is used to define the group. Although the summary
  doesnt need to be integrated into the tree, it can
  be particular effective if, as the user is exploring
  substrees, they can see a real-time summary of data
  associated with that group
end note

note right of U3
  Group could be a subtree or specific neighbours in
  tree
  Examples of downstream analysis:
  marker identification, summary of group meta-data,
  summary of VF and AMR genes
end note

note right of U4
  The scope of this view could be:
  1. Only genomes in group
  2. Group with of other related genomes in database
    i.e. The subtree that encompasses all genomes of
    interest
end note

note right of U5
  Users familiar with Ecoli phylogeny would be
  interested in relative position of genome in tree 
  i.e. outgroup, found in clade with known pathogenic strains
end note  

note right of U1
  Overlay of pertinent meta-data in tree can help
  identify traits in evolutionarily-related genomes
end note  

@enduml