#!/bin/bash
#This removes the old 'mithril' symlink from apache,
#and adds a new one; the new one points to the mithril
#index.html that is in the folder that the script is run on.
 
origin="$(pwd)"
static=${origin}/app/static/
apache="/var/www/html/mithril"
echo Making symlink from $static, to $apache
sudo rm $apache
sudo ln  $static $apache -s