#!/bin/bash
#This removes the old symlink from apache,
#and adds a new one; the new one points to the working 
#index.html that is in the folder that the script is run on.

default="none"
apache="/var/www/html/"
html_directory="/app/static/"

folder=${1:-${default}}
if [ "$folder" == "$default" ]
	then
	read -r -p "What folder in apache? " folder
fi

echo symlink = ${folder} ...

origin="$(pwd)"
static=${origin}${html_directory}
apachefolder=$apache$folder


[ -L $apachefolder ] && sudo rm $apachefolder && echo "Removing existing symlink at ${apachefolder} ..."
echo Making symlink from ${static}, to ${apachefolder} ...


sudo ln  $static $apachefolder -s

echo Apache Deployed!