#!/bin/bash
#Use this when you imported requirements and added another requirement to the environment.

source venv/bin/activate
pip freeze > venv/requirements.txt
freeze > venv/npm-requirements.txt
deactivate