#!/bin/bash
#Use this when you have both imported requirements
#AND added another requiremeent to the environment.

source venv/bin/activate
pip freeze > venv/requirements.txt
freeze > npm-requirements.txt
deactivate