#!/bin/bash
#starts up Blazegraph
echo Starting Blazegraph...
cd db
	java -server -Xmx4g -jar bigdata-bundled.jar <&- 1>/dev/null 2>&1 &
cd ..
sleep 10

#makes a superphy namespace
source venv/bin/activate
python ./python_package/uploader/main.py
deactivate