#!/bin/bash
#starts up Blazegraph
echo Starting Blazegraph...
java -server -Xmx4g -jar db/bigdata-bundled.jar <&- 1>/dev/null 2>&1 &
sleep 10

#makes a superphy namespace
source venv/bin/activate
python ./python_package/uploader/main.py
deactivate